name: Build and Release Apps (Hybrid - Native Android + EAS iOS)

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      upload_to_release:
        description: 'Upload to existing release (provide tag name)'
        required: false
        default: ''
      build_type:
        description: 'Build type'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - release

jobs:
  build-android:
    name: Build Android APK (Native)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm ci

      - name: Generate native code (prebuild)
        run: npx expo prebuild --platform android --no-install

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Prepare APK artifact
        run: |
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" | head -1)
          
          if [ -f "$APK_PATH" ]; then
            if [ "${{ github.event_name }}" = "release" ]; then
              FILENAME="obs-app-${{ github.event.release.tag_name }}.apk"
            elif [ "${{ github.event.inputs.upload_to_release }}" != "" ]; then
              FILENAME="obs-app-${{ github.event.inputs.upload_to_release }}.apk"
            else
              FILENAME="obs-app-${{ github.sha }}.apk"
            fi
            
            cp "$APK_PATH" "$FILENAME"
            echo "APK_FILENAME=$FILENAME" >> $GITHUB_ENV
          else
            echo "APK file not found"
            exit 1
          fi

      - name: Upload APK to Release
        if: github.event_name == 'release' || github.event.inputs.upload_to_release != ''
        run: |
          TAG_NAME="${{ github.event.release.tag_name || github.event.inputs.upload_to_release }}"
          gh release upload "$TAG_NAME" "${{ env.APK_FILENAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK as Artifact
        if: github.event_name != 'release' && github.event.inputs.upload_to_release == ''
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ env.APK_FILENAME }}
          retention-days: 30

  build-ios:
    name: Build iOS IPA (EAS)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm ci

      - name: Authenticate with Expo
        run: eas login
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS IPA
        run: eas build --platform ios --profile production --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download and Upload IPA
        run: |
          BUILD_URL=$(eas build:list --platform ios --limit 1 --json | jq -r '.[0].artifacts.buildUrl')
          
          if [ "$BUILD_URL" != "null" ] && [ -n "$BUILD_URL" ]; then
            if [ "${{ github.event_name }}" = "release" ]; then
              FILENAME="obs-app-${{ github.event.release.tag_name }}.ipa"
            elif [ "${{ github.event.inputs.upload_to_release }}" != "" ]; then
              FILENAME="obs-app-${{ github.event.inputs.upload_to_release }}.ipa"
            else
              FILENAME="obs-app-${{ github.sha }}.ipa"
            fi
            
            curl -L -o "$FILENAME" "$BUILD_URL"
            
            if [ "${{ github.event_name }}" = "release" ] || [ "${{ github.event.inputs.upload_to_release }}" != "" ]; then
              TAG_NAME="${{ github.event.release.tag_name || github.event.inputs.upload_to_release }}"
              gh release upload "$TAG_NAME" "$FILENAME"
            fi
            
            echo "IPA_FILENAME=$FILENAME" >> $GITHUB_ENV
          else
            echo "Failed to get build URL"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload IPA as Artifact
        if: github.event_name != 'release' && github.event.inputs.upload_to_release == ''
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ${{ env.IPA_FILENAME }}
          retention-days: 30 